import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import HeroHome from "../components/HeroHome";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeroHome />
    </Layout>
  );
}
