import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import GrayBanner from "../components/GrayBanner";
import TextImage from "../components/TextImage";
import homepageImage from "../public/assets/images/homepage.jpg";

export default function Home() {
  const heroHome = {
    title: "Welcome to Best Foot Forward K9 Training",
    subtitle: "Helping to create a happy and healthy relationship between you and your dog",
    buttonText: "See How",
    href: "/programs",
  };

  const bannerHome = {
    title: "Located in Wylie Texas servicing the greater Dallas Texas area",
    content: (
      <>
        <div className="city city1">Dallas</div>
        <div className="city city2">Plano</div>
        <div className="city city3">McKinney</div>
        <div className="city city4">Murphy</div>
        <div className="city city5">Allen</div>
        <div className="city city6">Richardson</div>
      </>
    ),
  };

  const textImage = {
    topHeader: "My Approach",
    header: "Does your dogs behavior have you at your wits end?",
    copy: "Dont worry there is hope. My permission based training techniques bring harmony to my clients who practice them consistently.",
    copy2:
      "My approach to dog training is geared towards addressing your dogs state of mind with a goal of creating a happy and balanced relationship between you and your dog.",
    image: <Image src={homepageImage} alt=" BFF K9 company logo" />,
  };

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero hero={heroHome} />
      <GrayBanner banner={bannerHome} />
      <TextImage content={textImage} />
    </Layout>
  );
}
